# Generated by Django 3.0.5 on 2020-04-21 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200421_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horario', models.TimeField(verbose_name='horário')),
                ('data_agendamento', models.DateTimeField(auto_now_add=True, verbose_name='data do agendamento')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='core.Medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia', 'horario'],
                'unique_together': {('dia', 'horario', 'paciente')},
            },
        ),
    ]
