# Generated by Django 3.0.5 on 2020-04-21 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendahora',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='core.Agenda'),
        ),
    ]
